!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PVFarm_GFL_GFM_2_1Dyn  ! 
!     SUBR    PVFarm_GFL_GFM_2Dyn  ! 
!     SUBR    3PHVSRC       ! 3-Phase Source model

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1
      REAL     Qs, Ps, Vrms_s, Isource(3), Vs(3)
      REAL     Vbase, Fbase, Q_inv1, P_inv1
      REAL     Vrms_inv1, I_inv1(3), V_inv1(3)
      REAL     Q_inv2, P_inv2, Vrms_inv2
      REAL     I_inv2(3), V_inv2(3), Qfault
      REAL     Pfault, Vrms_fault, Ifault(3)
      REAL     Vfault(3), Ibase, Irms_inv2
      REAL     Irms_s, Irms_fault, Irms_inv1
      REAL     Is(3)

! Internal Variables
      LOGICAL  LVD1_1
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 1
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 46
      NPGB      = NPGB + 40
      INODE     = NNODE + 2
      NNODE     = NNODE + 26
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 33
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      IT_1     = STOI(ISTOI + 1)
      Qs       = STOF(ISTOF + 1)
      Ps       = STOF(ISTOF + 2)
      Vrms_s   = STOF(ISTOF + 3)
      Vbase    = STOF(ISTOF + 10)
      Fbase    = STOF(ISTOF + 11)
      Q_inv1   = STOF(ISTOF + 12)
      P_inv1   = STOF(ISTOF + 13)
      Vrms_inv1 = STOF(ISTOF + 14)
      Q_inv2   = STOF(ISTOF + 21)
      P_inv2   = STOF(ISTOF + 22)
      Vrms_inv2 = STOF(ISTOF + 23)
      Qfault   = STOF(ISTOF + 30)
      Pfault   = STOF(ISTOF + 31)
      Vrms_fault = STOF(ISTOF + 32)
      Ibase    = STOF(ISTOF + 39)
      Irms_inv2 = STOF(ISTOF + 40)
      Irms_s   = STOF(ISTOF + 41)
      Irms_fault = STOF(ISTOF + 42)
      Irms_inv1 = STOF(ISTOF + 43)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Isource(IT_0) = STOF(ISTOF + 3 + IT_0)
         Vs(IT_0) = STOF(ISTOF + 6 + IT_0)
         I_inv1(IT_0) = STOF(ISTOF + 14 + IT_0)
         V_inv1(IT_0) = STOF(ISTOF + 17 + IT_0)
         I_inv2(IT_0) = STOF(ISTOF + 23 + IT_0)
         V_inv2(IT_0) = STOF(ISTOF + 26 + IT_0)
         Ifault(IT_0) = STOF(ISTOF + 32 + IT_0)
         Vfault(IT_0) = STOF(ISTOF + 35 + IT_0)
         Is(IT_0) = STOF(ISTOF + 43 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 'Hz'
      Fbase = 60.0

! 20:[const] Real Constant 'kV'
      Vbase = 120.0

! 30:[const] Real Constant 'kA'
      Ibase = 0.4811

! 40:[PVFarm_GFL_GFM_2_1]  
      CALL PVFarm_GFL_GFM_2_1Dyn()


! 60:[PVFarm_GFL_GFM_2]  
      CALL PVFarm_GFL_GFM_2Dyn()


! 90:[source_3] Three Phase Voltage Source Model 2 'Source 1'
! Three Phase Source: Source 1  Type: L
!  
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3  = 0.0*PI_BY180
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF  = NRTCF + 4
      CALL EMTDC_3PHVSRC(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3), RVD1_4, .T&
     &RUE., RVD1_1 , RVD1_2, RVD1_3)
!

! 190:[tfaultn] Timed Fault Logic 
! Timed fault logic
      IT_1 = 0
      IF ( TIME .GE. 1.0 ) IT_1 = 1
      IF ( TIME .GE. (1.0+3.0) ) IT_1 = 0

! 300:[tpflt] Three Phase Fault 
      CALL E3PHFLT1_EXE(SS, (IBRCH+10), (IBRCH+11), (IBRCH+12), (IBRCH+1&
     &3), (IBRCH+14), (IBRCH+15),0,IT_1,7,0.5)
      LVD1_1 = (OPENBR( (IBRCH+10),SS).AND.OPENBR( (IBRCH+11),SS).AND.OP&
     &ENBR( (IBRCH+12),SS).AND.OPENBR( (IBRCH+13),SS).AND.OPENBR( (IBRCH&
     &+14),SS).AND.OPENBR( (IBRCH+15),SS))
      IVD1_1 = E_BtoI(LVD1_1)
      IF(FIRSTSTEP .OR. (IVD1_1 .NE. STORI(NSTORI))) THEN
         CALL PSCAD_AGI2(ICALL_NO,505792052,1-IVD1_1,"AG1")
         STORI(NSTORI) = IVD1_1
      ENDIF
      NSTORI = NSTORI + 1

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 1) = Qs
      STOF(ISTOF + 2) = Ps
      STOF(ISTOF + 3) = Vrms_s
      STOF(ISTOF + 10) = Vbase
      STOF(ISTOF + 11) = Fbase
      STOF(ISTOF + 12) = Q_inv1
      STOF(ISTOF + 13) = P_inv1
      STOF(ISTOF + 14) = Vrms_inv1
      STOF(ISTOF + 21) = Q_inv2
      STOF(ISTOF + 22) = P_inv2
      STOF(ISTOF + 23) = Vrms_inv2
      STOF(ISTOF + 30) = Qfault
      STOF(ISTOF + 31) = Pfault
      STOF(ISTOF + 32) = Vrms_fault
      STOF(ISTOF + 39) = Ibase
      STOF(ISTOF + 40) = Irms_inv2
      STOF(ISTOF + 41) = Irms_s
      STOF(ISTOF + 42) = Irms_fault
      STOF(ISTOF + 43) = Irms_inv1

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 3 + IT_0) = Isource(IT_0)
         STOF(ISTOF + 6 + IT_0) = Vs(IT_0)
         STOF(ISTOF + 14 + IT_0) = I_inv1(IT_0)
         STOF(ISTOF + 17 + IT_0) = V_inv1(IT_0)
         STOF(ISTOF + 23 + IT_0) = I_inv2(IT_0)
         STOF(ISTOF + 26 + IT_0) = V_inv2(IT_0)
         STOF(ISTOF + 32 + IT_0) = Ifault(IT_0)
         STOF(ISTOF + 35 + IT_0) = Vfault(IT_0)
         STOF(ISTOF + 43 + IT_0) = Is(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PVFarm_GFL_GFM_2_1Out  ! 
      REAL    EMTDC_VVDC    ! 
      REAL    P3PH3         ! 
      REAL    Q3PH3         ! 
!     SUBR    DGTL_RMS3     ! '3 Phase Digital RMS Meter'
!     SUBR    DGTL_RMS3A    ! '3 Phase Digital RMS Meter'
!     SUBR    MPHASE3PS     ! Phase Measurement in a 3p signal
!     SUBR    PVFarm_GFL_GFM_2Out  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  Bus3(3), NT_1(3), NT_2(3), NT_3(3)

! Control Signals
      REAL     Qs, Ps, Vrms_s, Isource(3), Vs(3)
      REAL     Vbase, Fbase, Q_inv1, P_inv1
      REAL     Vrms_inv1, I_inv1(3), V_inv1(3)
      REAL     Q_inv2, P_inv2, Vrms_inv2
      REAL     I_inv2(3), V_inv2(3), Qfault
      REAL     Pfault, Vrms_fault, Ifault(3)
      REAL     Vfault(3), Ibase, Irms_inv2
      REAL     Irms_s, Irms_fault, Irms_inv1
      REAL     Is(3)

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 40
      INODE     = NNODE + 2
      NNODE     = NNODE + 26
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 33
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Qs       = STOF(ISTOF + 1)
      Ps       = STOF(ISTOF + 2)
      Vrms_s   = STOF(ISTOF + 3)
      Vbase    = STOF(ISTOF + 10)
      Fbase    = STOF(ISTOF + 11)
      Q_inv1   = STOF(ISTOF + 12)
      P_inv1   = STOF(ISTOF + 13)
      Vrms_inv1 = STOF(ISTOF + 14)
      Q_inv2   = STOF(ISTOF + 21)
      P_inv2   = STOF(ISTOF + 22)
      Vrms_inv2 = STOF(ISTOF + 23)
      Qfault   = STOF(ISTOF + 30)
      Pfault   = STOF(ISTOF + 31)
      Vrms_fault = STOF(ISTOF + 32)
      Ibase    = STOF(ISTOF + 39)
      Irms_inv2 = STOF(ISTOF + 40)
      Irms_s   = STOF(ISTOF + 41)
      Irms_fault = STOF(ISTOF + 42)
      Irms_inv1 = STOF(ISTOF + 43)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Isource(IT_0) = STOF(ISTOF + 3 + IT_0)
         Vs(IT_0) = STOF(ISTOF + 6 + IT_0)
         I_inv1(IT_0) = STOF(ISTOF + 14 + IT_0)
         V_inv1(IT_0) = STOF(ISTOF + 17 + IT_0)
         I_inv2(IT_0) = STOF(ISTOF + 23 + IT_0)
         V_inv2(IT_0) = STOF(ISTOF + 26 + IT_0)
         Ifault(IT_0) = STOF(ISTOF + 32 + IT_0)
         Vfault(IT_0) = STOF(ISTOF + 35 + IT_0)
         Is(IT_0) = STOF(ISTOF + 43 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         Bus3(IT_0) = NODE(INODE + 6 + IT_0)
         NT_1(IT_0) = NODE(INODE + 12 + IT_0)
         NT_2(IT_0) = NODE(INODE + 15 + IT_0)
         NT_3(IT_0) = NODE(INODE + 18 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 'Hz'

      Fbase = 60.0

! 20:[const] Real Constant 'kV'

      Vbase = 120.0

! 30:[const] Real Constant 'kA'

      Ibase = 0.4811

! 40:[PVFarm_GFL_GFM_2_1]  
      CALL PVFarm_GFL_GFM_2_1Out()


! 50:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      I_inv1(1) = ( CBR((IBRCH+7), SS))
      I_inv1(2) = ( CBR((IBRCH+8), SS))
      I_inv1(3) = ( CBR((IBRCH+9), SS))
      V_inv1(1) = EMTDC_VVDC(SS, NT_1(1), NT_1(2))
      V_inv1(2) = EMTDC_VVDC(SS, NT_1(2), NT_1(3))
      V_inv1(3) = EMTDC_VVDC(SS, NT_1(3), NT_1(1))
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+7), (IBRCH+8), (IBRCH+9),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,896705196,RVD1_1,"Pd")
      P_inv1 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+7), (IBRCH+8), (IBRCH+9),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,896705196,RVD1_1,"Qd")
      Q_inv1 = RVD1_1
      CALL DGTL_RMS3(256,SS,NT_1(1),NT_1(2),NT_1(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,896705196,RVD1_1,"Vd")
      Vrms_inv1 = RVD1_1
      CALL DGTL_RMS3A(256,( CBR((IBRCH+7), SS)),( CBR((IBRCH+8), SS)),( &
     &CBR((IBRCH+9), SS)),RTCF(IVD1_1+3),RTCF(IVD1_1+4),0.0,RVD1_1)
      Irms_inv1 = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS, NT_1(1), 0)
      RVD1_3 = EMTDC_VVDC(SS, NT_1(2), 0)
      RVD1_4 = EMTDC_VVDC(SS, NT_1(3), 0)
      CALL MPHASE3PS(1, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,896705196,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,896705196,1,"hide2")
      ENDIF

! 60:[PVFarm_GFL_GFM_2]  
      CALL PVFarm_GFL_GFM_2Out()


! 70:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Ifault(1) = ( CBR((IBRCH+19), SS))
      Ifault(2) = ( CBR((IBRCH+20), SS))
      Ifault(3) = ( CBR((IBRCH+21), SS))
      Vfault(1) = EMTDC_VVDC(SS, Bus3(1), Bus3(2))
      Vfault(2) = EMTDC_VVDC(SS, Bus3(2), Bus3(3))
      Vfault(3) = EMTDC_VVDC(SS, Bus3(3), Bus3(1))
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+19), (IBRCH+20), (IBRCH+2&
     &1),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1156213913,RVD1_1,"Pd")
      Pfault = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+19), (IBRCH+20), (IBRCH+2&
     &1),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1156213913,RVD1_1,"Qd")
      Qfault = RVD1_1
      CALL DGTL_RMS3(256,SS,Bus3(1),Bus3(2),Bus3(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1156213913,RVD1_1,"Vd")
      Vrms_fault = RVD1_1
      CALL DGTL_RMS3A(256,( CBR((IBRCH+19), SS)),( CBR((IBRCH+20), SS)),&
     &( CBR((IBRCH+21), SS)),RTCF(IVD1_1+3),RTCF(IVD1_1+4),0.0,RVD1_1)
      Irms_fault = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS, Bus3(1), 0)
      RVD1_3 = EMTDC_VVDC(SS, Bus3(2), 0)
      RVD1_4 = EMTDC_VVDC(SS, Bus3(3), 0)
      CALL MPHASE3PS(1, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,1156213913,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,1156213913,1,"hide2")
      ENDIF

! 80:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Isource(1) = ( CBR((IBRCH+16), SS))
      Isource(2) = ( CBR((IBRCH+17), SS))
      Isource(3) = ( CBR((IBRCH+18), SS))
      Vs(1) = EMTDC_VVDC(SS, NT_3(1), NT_3(2))
      Vs(2) = EMTDC_VVDC(SS, NT_3(2), NT_3(3))
      Vs(3) = EMTDC_VVDC(SS, NT_3(3), NT_3(1))
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+16), (IBRCH+17), (IBRCH+1&
     &8),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,889026531,RVD1_1,"Pd")
      Ps = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+16), (IBRCH+17), (IBRCH+1&
     &8),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,889026531,RVD1_1,"Qd")
      Qs = RVD1_1
      CALL DGTL_RMS3(256,SS,NT_3(1),NT_3(2),NT_3(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,889026531,RVD1_1,"Vd")
      Vrms_s = RVD1_1
      CALL DGTL_RMS3A(256,( CBR((IBRCH+16), SS)),( CBR((IBRCH+17), SS)),&
     &( CBR((IBRCH+18), SS)),RTCF(IVD1_1+3),RTCF(IVD1_1+4),0.0,RVD1_1)
      Irms_s = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS, NT_3(1), 0)
      RVD1_3 = EMTDC_VVDC(SS, NT_3(2), 0)
      RVD1_4 = EMTDC_VVDC(SS, NT_3(3), 0)
      CALL MPHASE3PS(1, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,889026531,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,889026531,1,"hide2")
      ENDIF

! 90:[source_3] Three Phase Voltage Source Model 2 'Source 1'
      Is(1) = ( CBR((IBRCH+1), SS))
      Is(2) = ( CBR((IBRCH+2), SS))
      Is(3) = ( CBR((IBRCH+3), SS))

! 100:[pgb] Output Channel 'V_inv1'

      DO IVD1_1 = 1, 3
         PGB(IPGB+1+IVD1_1-1) = V_inv1(IVD1_1)
      ENDDO

! 110:[pgb] Output Channel 'I_inv1'

      DO IVD1_1 = 1, 3
         PGB(IPGB+4+IVD1_1-1) = I_inv1(IVD1_1)
      ENDDO

! 120:[pgb] Output Channel 'Vfault'

      DO IVD1_1 = 1, 3
         PGB(IPGB+7+IVD1_1-1) = Vfault(IVD1_1)
      ENDDO

! 130:[pgb] Output Channel 'Vrms_inv1'

      PGB(IPGB+10) = Vrms_inv1

! 140:[pgb] Output Channel 'Ifault'

      DO IVD1_1 = 1, 3
         PGB(IPGB+11+IVD1_1-1) = Ifault(IVD1_1)
      ENDDO

! 150:[pgb] Output Channel 'Irms_inv1'

      PGB(IPGB+14) = Irms_inv1

! 160:[pgb] Output Channel 'Vrms_fault'

      PGB(IPGB+15) = Vrms_fault

! 170:[pgb] Output Channel 'P_inv1'

      PGB(IPGB+16) = P_inv1

! 180:[pgb] Output Channel 'Irms_fault'

      PGB(IPGB+17) = Irms_fault

! 200:[pgb] Output Channel 'Q_inv1'

      PGB(IPGB+18) = Q_inv1

! 210:[pgb] Output Channel 'Pfault'

      PGB(IPGB+19) = Pfault

! 220:[pgb] Output Channel 'Vs'

      DO IVD1_1 = 1, 3
         PGB(IPGB+20+IVD1_1-1) = Vs(IVD1_1)
      ENDDO

! 230:[pgb] Output Channel 'Qfault'

      PGB(IPGB+23) = Qfault

! 240:[pgb] Output Channel 'Isource'

      DO IVD1_1 = 1, 3
         PGB(IPGB+24+IVD1_1-1) = Isource(IVD1_1)
      ENDDO

! 250:[pgb] Output Channel 'Vrms_s'

      PGB(IPGB+27) = Vrms_s

! 260:[pgb] Output Channel 'Irms_s'

      PGB(IPGB+28) = Irms_s

! 270:[pgb] Output Channel 'Ps'

      PGB(IPGB+29) = Ps

! 280:[pgb] Output Channel 'Qs'

      PGB(IPGB+30) = Qs

! 290:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      I_inv2(1) = ( CBR((IBRCH+4), SS))
      I_inv2(2) = ( CBR((IBRCH+5), SS))
      I_inv2(3) = ( CBR((IBRCH+6), SS))
      V_inv2(1) = EMTDC_VVDC(SS, NT_2(1), NT_2(2))
      V_inv2(2) = EMTDC_VVDC(SS, NT_2(2), NT_2(3))
      V_inv2(3) = EMTDC_VVDC(SS, NT_2(3), NT_2(1))
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+4), (IBRCH+5), (IBRCH+6),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1044838951,RVD1_1,"Pd")
      P_inv2 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+4), (IBRCH+5), (IBRCH+6),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1044838951,RVD1_1,"Qd")
      Q_inv2 = RVD1_1
      CALL DGTL_RMS3(256,SS,NT_2(1),NT_2(2),NT_2(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1044838951,RVD1_1,"Vd")
      Vrms_inv2 = RVD1_1
      CALL DGTL_RMS3A(256,( CBR((IBRCH+4), SS)),( CBR((IBRCH+5), SS)),( &
     &CBR((IBRCH+6), SS)),RTCF(IVD1_1+3),RTCF(IVD1_1+4),0.0,RVD1_1)
      Irms_inv2 = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS, NT_2(1), 0)
      RVD1_3 = EMTDC_VVDC(SS, NT_2(2), 0)
      RVD1_4 = EMTDC_VVDC(SS, NT_2(3), 0)
      CALL MPHASE3PS(1, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,1044838951,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,1044838951,1,"hide2")
      ENDIF

! 300:[tpflt] Three Phase Fault 
!
! Multi-phase Fault Currents
!

! 310:[pgb] Output Channel 'Q_inv2'

      PGB(IPGB+31) = Q_inv2

! 320:[pgb] Output Channel 'P_inv2'

      PGB(IPGB+32) = P_inv2

! 330:[pgb] Output Channel 'Irms_inv2'

      PGB(IPGB+33) = Irms_inv2

! 340:[pgb] Output Channel 'Vrms_inv2'

      PGB(IPGB+34) = Vrms_inv2

! 350:[pgb] Output Channel 'I_inv2'

      DO IVD1_1 = 1, 3
         PGB(IPGB+35+IVD1_1-1) = I_inv2(IVD1_1)
      ENDDO

! 360:[pgb] Output Channel 'V_inv2'

      DO IVD1_1 = 1, 3
         PGB(IPGB+38+IVD1_1-1) = V_inv2(IVD1_1)
      ENDDO

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Qs
      STOF(ISTOF + 2) = Ps
      STOF(ISTOF + 3) = Vrms_s
      STOF(ISTOF + 10) = Vbase
      STOF(ISTOF + 11) = Fbase
      STOF(ISTOF + 12) = Q_inv1
      STOF(ISTOF + 13) = P_inv1
      STOF(ISTOF + 14) = Vrms_inv1
      STOF(ISTOF + 21) = Q_inv2
      STOF(ISTOF + 22) = P_inv2
      STOF(ISTOF + 23) = Vrms_inv2
      STOF(ISTOF + 30) = Qfault
      STOF(ISTOF + 31) = Pfault
      STOF(ISTOF + 32) = Vrms_fault
      STOF(ISTOF + 39) = Ibase
      STOF(ISTOF + 40) = Irms_inv2
      STOF(ISTOF + 41) = Irms_s
      STOF(ISTOF + 42) = Irms_fault
      STOF(ISTOF + 43) = Irms_inv1

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 3 + IT_0) = Isource(IT_0)
         STOF(ISTOF + 6 + IT_0) = Vs(IT_0)
         STOF(ISTOF + 14 + IT_0) = I_inv1(IT_0)
         STOF(ISTOF + 17 + IT_0) = V_inv1(IT_0)
         STOF(ISTOF + 23 + IT_0) = I_inv2(IT_0)
         STOF(ISTOF + 26 + IT_0) = V_inv2(IT_0)
         STOF(ISTOF + 32 + IT_0) = Ifault(IT_0)
         STOF(ISTOF + 35 + IT_0) = Vfault(IT_0)
         STOF(ISTOF + 43 + IT_0) = Is(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PVFarm_GFL_GFM_2_1Dyn_Begin  ! 
!     SUBR    PVFarm_GFL_GFM_2Dyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     Vbase, Fbase, Ibase

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 26
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 33
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 'Hz'
      Fbase = 60.0

! 20:[const] Real Constant 'kV'
      Vbase = 120.0

! 30:[const] Real Constant 'kA'
      Ibase = 0.4811

! 40:[PVFarm_GFL_GFM_2_1]  
      CALL PVFarm_GFL_GFM_2_1Dyn_Begin()


! 60:[PVFarm_GFL_GFM_2]  
      CALL PVFarm_GFL_GFM_2Dyn_Begin()


! 90:[source_3] Three Phase Voltage Source Model 2 'Source 1'
      IF (0.04 .LE. 1.0E-38) THEN
        CALL E_BRANCH_CFG( (IBRCH+1),SS,1,0,0,1.0E-38,0.0,0.0)
        CALL E_BRANCH_CFG( (IBRCH+2),SS,1,0,0,1.0E-38,0.0,0.0)
        CALL E_BRANCH_CFG( (IBRCH+3),SS,1,0,0,1.0E-38,0.0,0.0)
      ELSE
        CALL E_BRANCH_CFG( (IBRCH+1),SS,0,1,0,0.0,0.04,0.0)
        CALL E_BRANCH_CFG( (IBRCH+2),SS,0,1,0,0.0,0.04,0.0)
        CALL E_BRANCH_CFG( (IBRCH+3),SS,0,1,0,0.0,0.04,0.0)
      ENDIF
      RTCF(NRTCF)   = 120.0*SQRT_2*SQRT_1BY3
      RTCF(NRTCF+1) = 60.0*TWO_PI
      RTCF(NRTCF+3) = 0.05
      NRTCF = NRTCF + 4

! 300:[tpflt] Three Phase Fault 
      CALL E3PHFLT1_CFG(1000000.0,0.0)

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PVFarm_GFL_GFM_2_1Out_Begin  ! 
!     SUBR    PVFarm_GFL_GFM_2Out_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  Bus3(3), NT_1(3), NT_2(3), NT_3(3)

! Control Signals
      REAL     Vbase, Fbase, Ibase

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 26
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 33
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         Bus3(IT_0) = NODE(INODE + 6 + IT_0)
         NT_1(IT_0) = NODE(INODE + 12 + IT_0)
         NT_2(IT_0) = NODE(INODE + 15 + IT_0)
         NT_3(IT_0) = NODE(INODE + 18 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 'Hz'
      Fbase = 60.0

! 20:[const] Real Constant 'kV'
      Vbase = 120.0

! 30:[const] Real Constant 'kA'
      Ibase = 0.4811

! 40:[PVFarm_GFL_GFM_2_1]  
      CALL PVFarm_GFL_GFM_2_1Out_Begin()


! 50:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(Vbase) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vbase)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = Fbase
      IF (ABS(Ibase) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(Ibase)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 60:[PVFarm_GFL_GFM_2]  
      CALL PVFarm_GFL_GFM_2Out_Begin()


! 70:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(Vbase) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vbase)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = Fbase
      IF (ABS(Ibase) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(Ibase)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 80:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(Vbase) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vbase)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = Fbase
      IF (ABS(Ibase) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(Ibase)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 100:[pgb] Output Channel 'V_inv1'

! 110:[pgb] Output Channel 'I_inv1'

! 120:[pgb] Output Channel 'Vfault'

! 130:[pgb] Output Channel 'Vrms_inv1'

! 140:[pgb] Output Channel 'Ifault'

! 150:[pgb] Output Channel 'Irms_inv1'

! 160:[pgb] Output Channel 'Vrms_fault'

! 170:[pgb] Output Channel 'P_inv1'

! 180:[pgb] Output Channel 'Irms_fault'

! 200:[pgb] Output Channel 'Q_inv1'

! 210:[pgb] Output Channel 'Pfault'

! 220:[pgb] Output Channel 'Vs'

! 230:[pgb] Output Channel 'Qfault'

! 240:[pgb] Output Channel 'Isource'

! 250:[pgb] Output Channel 'Vrms_s'

! 260:[pgb] Output Channel 'Irms_s'

! 270:[pgb] Output Channel 'Ps'

! 280:[pgb] Output Channel 'Qs'

! 290:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(Vbase) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vbase)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = Fbase
      IF (ABS(Ibase) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(Ibase)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 310:[pgb] Output Channel 'Q_inv2'

! 320:[pgb] Output Channel 'P_inv2'

! 330:[pgb] Output Channel 'Irms_inv2'

! 340:[pgb] Output Channel 'Vrms_inv2'

! 350:[pgb] Output Channel 'I_inv2'

! 360:[pgb] Output Channel 'V_inv2'

      RETURN
      END

