!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : EPRI_PLL_18_1
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE EPRI_PLL_18_1Dyn(freq, theta, Vabc, VRT, Kppll,        &
     &   Kipll_T, Wmax, Dblk)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
!     SUBR    EMTDC_XMSTAB  ! 'Monostable Multivibrator /w Interpolation'
!     SUBR    TRDQO         ! DQ0 transformation
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'
      REAL    LIMIT         ! Hard Limiter

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Vabc(3), VRT, Kppll
      REAL,    INTENT(IN)  :: Kipll_T, Wmax, Dblk
      REAL,    INTENT(OUT) :: freq, theta

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5
      REAL     Kipll_max, Kipll_min, RT_6, RT_7
      REAL     theta_int, RT_8, RT_9, RT_10
      REAL     RT_11, w_pll, RT_12, RT_13, RT_14
      REAL     RT_15, RT_16, RT_17, RT_18(2)
      REAL     Vpvd, Vpvq, Wmin, RT_19, RT_20
      REAL     RT_21

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD2_1(2), RVD2_2(2), RVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 1
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 39
      IPGB      = NPGB
      NPGB      = NPGB + 2
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      freq     = STOF(ISTOF + 1)
      theta    = STOF(ISTOF + 2)
      RT_1     = STOF(ISTOF + 11)
      RT_2     = STOF(ISTOF + 12)
      RT_3     = STOF(ISTOF + 13)
      RT_4     = STOF(ISTOF + 14)
      RT_5     = STOF(ISTOF + 15)
      Kipll_max = STOF(ISTOF + 16)
      Kipll_min = STOF(ISTOF + 17)
      RT_6     = STOF(ISTOF + 18)
      RT_7     = STOF(ISTOF + 19)
      IT_1     = STOI(ISTOI + 1)
      theta_int = STOF(ISTOF + 20)
      RT_8     = STOF(ISTOF + 21)
      RT_9     = STOF(ISTOF + 22)
      RT_10    = STOF(ISTOF + 23)
      RT_11    = STOF(ISTOF + 24)
      w_pll    = STOF(ISTOF + 25)
      RT_12    = STOF(ISTOF + 26)
      RT_13    = STOF(ISTOF + 27)
      RT_14    = STOF(ISTOF + 28)
      RT_15    = STOF(ISTOF + 29)
      RT_16    = STOF(ISTOF + 30)
      RT_17    = STOF(ISTOF + 31)
      Vpvd     = STOF(ISTOF + 34)
      Vpvq     = STOF(ISTOF + 35)
      Wmin     = STOF(ISTOF + 36)
      RT_19    = STOF(ISTOF + 37)
      RT_20    = STOF(ISTOF + 38)
      RT_21    = STOF(ISTOF + 39)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         RT_18(IT_0) = STOF(ISTOF + 31 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'EPRI_PLL_18_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[const] Real Constant 
      RT_8 = 120.0

! 60:[datatap] Scalar/Array Tap 
      RT_14 = Vabc(1)

! 80:[datatap] Scalar/Array Tap 
      RT_15 = Vabc(2)

! 90:[gain] Gain Block 
!  Gain
      Wmin = -1.0 * Wmax

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_9 = PI_

! 120:[datatap] Scalar/Array Tap 
      RT_16 = Vabc(3)

! 130:[const] Real Constant 
      RT_3 = 0.0

! 140:[const] Real Constant 
      RT_20 = 0.0

! 150:[time-sig] Output of Simulation Time 
      RT_21 = TIME

! 160:[emtconst] Commonly Used Constants (pi...) 
      RT_13 = TWO_PI

! 170:[gain] Gain Block 
!  Gain
      RT_12 = 60.0 * RT_13

! 180:[mult] Multiplier 
      RT_10 = RT_8 * RT_9

! 190:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,Dblk,RT_21,0.0,0.0,1.0,RVD2_1)
      RT_19 = RVD2_1(1)

! 200:[monostable] Interpolated Monostable MultiVibrator 
!
      RVD2_1(1) = FLOAT(NINT(RT_19))
      RVD2_1(2) = 0.0
      CALL EMTDC_XMSTAB(0,0.1,RVD2_1,RVD2_2)
      IT_1 = NINT(RVD2_2(1))


! 210:[select] Two Input Selector 
      IF (NINT(VRT) .EQ. RTCI(NRTCI)) THEN
         RT_4 = Vpvq
      ELSE
         RT_4 = RT_3
      ENDIF
      NRTCI = NRTCI + 1
!

! 220:[gain] Gain Block 
!  Gain
      RT_6 = Kppll * Vpvq

! 230:[abcdq0] abc dq0 transformation 
!ABC to DQ0 transformation
      CALL TRDQO(RT_14,RT_15,RT_16,Vpvd,Vpvq,RT_17,theta_int,1)
      Vpvq = -Vpvq

! 240:[mult] Multiplier 
      RT_5 = Vpvq * Kppll

! 250:[sumjct] Summing/Differencing Junctions 
      Kipll_max = + Wmax - RT_5

! 260:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_4
      RVD2_1(2) = 0.0
      RVD2_2(1) = FLOAT(IT_1)
      RVD2_2(2) = 0.0
      RT_7 = EMTDC_XINT(0, 0, 1, RVD1_1, Kipll_T, 0.0, Kipll_min, Kipll_&
     &max, RVD2_2, RVD2_1)

! 270:[sumjct] Summing/Differencing Junctions 
      RT_1 = + RT_6 + RT_7

! 280:[hardlimit_57_1] Hard Limiter 
!  Hard_Limit
      IF (Wmin .LE. Wmax) THEN
        RT_2 = LIMIT(Wmin, Wmax, RT_1)
      ELSE
        RT_2 = RT_1
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,1786741054,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 290:[select] Two Input Selector 
      IF (NINT(RT_19) .EQ. RTCI(NRTCI)) THEN
         RT_11 = RT_2
      ELSE
         RT_11 = RT_20
      ENDIF
      NRTCI = NRTCI + 1
!

! 300:[sumjct] Summing/Differencing Junctions 
      w_pll = + RT_10 + RT_11

! 310:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = w_pll
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      theta_int = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -10000000000.0, &
     &10000000000.0, RVD2_2, RVD2_1)

! 320:[gain] Gain Block 
!  Gain
      Kipll_min = -1.0 * Kipll_max

! 330:[div] Divider 
      IF (ABS(RT_12) .LT. 1.0E-100) THEN
         IF (RT_12 .LT. 0.0)  THEN
            freq = -1.0E100 * w_pll
         ELSE
            freq =  1.0E100 * w_pll
         ENDIF
      ELSE
         freq = w_pll / RT_12
      ENDIF

! 340:[gain] Gain Block 
!  Gain
      theta = 1.0 * theta_int

! 360:[datamerge] Merges data signals into an array 
      RT_18(1) = Vpvd
      RT_18(2) = Vpvq

! 370:[pgb] Output Channel 'Vdq'

      DO IVD1_1 = 1, 2
         PGB(IPGB+1+IVD1_1-1) = RT_18(IVD1_1)
      ENDDO

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = freq
      STOF(ISTOF + 2) = theta
      STOF(ISTOF + 6) = VRT
      STOF(ISTOF + 7) = Kppll
      STOF(ISTOF + 8) = Kipll_T
      STOF(ISTOF + 9) = Wmax
      STOF(ISTOF + 10) = Dblk
      STOF(ISTOF + 11) = RT_1
      STOF(ISTOF + 12) = RT_2
      STOF(ISTOF + 13) = RT_3
      STOF(ISTOF + 14) = RT_4
      STOF(ISTOF + 15) = RT_5
      STOF(ISTOF + 16) = Kipll_max
      STOF(ISTOF + 17) = Kipll_min
      STOF(ISTOF + 18) = RT_6
      STOF(ISTOF + 19) = RT_7
      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 20) = theta_int
      STOF(ISTOF + 21) = RT_8
      STOF(ISTOF + 22) = RT_9
      STOF(ISTOF + 23) = RT_10
      STOF(ISTOF + 24) = RT_11
      STOF(ISTOF + 25) = w_pll
      STOF(ISTOF + 26) = RT_12
      STOF(ISTOF + 27) = RT_13
      STOF(ISTOF + 28) = RT_14
      STOF(ISTOF + 29) = RT_15
      STOF(ISTOF + 30) = RT_16
      STOF(ISTOF + 31) = RT_17
      STOF(ISTOF + 34) = Vpvd
      STOF(ISTOF + 35) = Vpvq
      STOF(ISTOF + 36) = Wmin
      STOF(ISTOF + 37) = RT_19
      STOF(ISTOF + 38) = RT_20
      STOF(ISTOF + 39) = RT_21

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 31 + IT_0) = RT_18(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 2 + IT_0) = Vabc(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !freq     is output
      !theta    is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE EPRI_PLL_18_1Out()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_8, RT_9, RT_13, RT_20

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 2
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_3     = STOF(ISTOF + 13)
      RT_8     = STOF(ISTOF + 21)
      RT_9     = STOF(ISTOF + 22)
      RT_13    = STOF(ISTOF + 27)
      RT_20    = STOF(ISTOF + 38)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'EPRI_PLL_18_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[const] Real Constant 

      RT_8 = 120.0

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_9 = PI_

! 130:[const] Real Constant 

      RT_3 = 0.0

! 140:[const] Real Constant 

      RT_20 = 0.0

! 160:[emtconst] Commonly Used Constants (pi...) 
      RT_13 = TWO_PI

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 13) = RT_3
      STOF(ISTOF + 21) = RT_8
      STOF(ISTOF + 22) = RT_9
      STOF(ISTOF + 27) = RT_13
      STOF(ISTOF + 38) = RT_20


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE EPRI_PLL_18_1Dyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_8, RT_9, RT_13, RT_20

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[const] Real Constant 
      RT_8 = 120.0

! 60:[datatap] Scalar/Array Tap 

! 80:[datatap] Scalar/Array Tap 

! 90:[gain] Gain Block 

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_9 = PI_

! 120:[datatap] Scalar/Array Tap 

! 130:[const] Real Constant 
      RT_3 = 0.0

! 140:[const] Real Constant 
      RT_20 = 0.0

! 150:[time-sig] Output of Simulation Time 

! 160:[emtconst] Commonly Used Constants (pi...) 
      RT_13 = TWO_PI

! 170:[gain] Gain Block 

! 180:[mult] Multiplier 

! 190:[compare] Single Input Level Comparator 

! 200:[monostable] Interpolated Monostable MultiVibrator 

! 210:[select] Two Input Selector 
      RTCI(NRTCI) = 0
      NRTCI = NRTCI + 1

! 220:[gain] Gain Block 

! 230:[abcdq0] abc dq0 transformation 

! 240:[mult] Multiplier 

! 250:[sumjct] Summing/Differencing Junctions 

! 260:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 270:[sumjct] Summing/Differencing Junctions 

! 280:[hardlimit_57_1] Hard Limiter 

! 290:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 300:[sumjct] Summing/Differencing Junctions 

! 310:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 320:[gain] Gain Block 

! 330:[div] Divider 

! 340:[gain] Gain Block 

! 360:[datamerge] Merges data signals into an array 

! 370:[pgb] Output Channel 'Vdq'

      RETURN
      END

!=======================================================================

      SUBROUTINE EPRI_PLL_18_1Out_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_8, RT_9, RT_13, RT_20

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[const] Real Constant 
      RT_8 = 120.0

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_9 = PI_

! 130:[const] Real Constant 
      RT_3 = 0.0

! 140:[const] Real Constant 
      RT_20 = 0.0

! 160:[emtconst] Commonly Used Constants (pi...) 
      RT_13 = TWO_PI

      RETURN
      END

