!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Sys_2_1
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Sys_2_1Dyn()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    REALPOLE      ! 
!     SUBR    EPRI_PLL_18_1Dyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, BRK_Load1, BRK_Load2
      REAL     RT_1, RT_2, RT_3(3), RT_4, Pbus1
      REAL     Pbus2, Pbus3, RT_5(3), Qbus1
      REAL     Qbus2, Qbus3, RT_6(3), Vbus1
      REAL     Vbus2, Vbus3, RT_7(3), Ibus1, RT_8
      REAL     RT_9, RT_10, Vload_abc(3), RT_11

! Internal Variables
      LOGICAL  LVD1_1
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 3
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 32
      IPGB      = NPGB
      NPGB      = NPGB + 11
      INODE     = NNODE + 2
      NNODE     = NNODE + 26
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 63
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_4     = STOF(ISTOF + 6)
      Pbus1    = STOF(ISTOF + 7)
      Pbus2    = STOF(ISTOF + 8)
      Pbus3    = STOF(ISTOF + 9)
      Qbus1    = STOF(ISTOF + 13)
      Qbus2    = STOF(ISTOF + 14)
      Qbus3    = STOF(ISTOF + 15)
      Vbus1    = STOF(ISTOF + 19)
      Vbus2    = STOF(ISTOF + 20)
      Vbus3    = STOF(ISTOF + 21)
      Ibus1    = STOF(ISTOF + 25)
      IT_1     = STOI(ISTOI + 1)
      RT_8     = STOF(ISTOF + 26)
      RT_9     = STOF(ISTOF + 27)
      RT_10    = STOF(ISTOF + 28)
      RT_11    = STOF(ISTOF + 32)
      BRK_Load1 = STOI(ISTOI + 2)
      BRK_Load2 = STOI(ISTOI + 3)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_3(IT_0) = STOF(ISTOF + 2 + IT_0)
         RT_5(IT_0) = STOF(ISTOF + 9 + IT_0)
         RT_6(IT_0) = STOF(ISTOF + 15 + IT_0)
         RT_7(IT_0) = STOF(ISTOF + 21 + IT_0)
         Vload_abc(IT_0) = STOF(ISTOF + 28 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Sys_2_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[tfaultn] Timed Fault Logic 
! Timed fault logic
      IT_1 = 0
      IF ( TIME .GE. 5.0 ) IT_1 = 1
      IF ( TIME .GE. (5.0+0.1) ) IT_1 = 0

! 50:[tbreakn] Timed Breaker Logic 
! Timed breaker logic
      IF ( TIMEZERO ) THEN
         BRK_Load1 = 1
      ELSE
         BRK_Load1 = 1
         IF ( TIME .GE. 3.0 ) BRK_Load1 = (1-1)
      ENDIF

! 60:[tbreakn] Timed Breaker Logic 
! Timed breaker logic
      IF ( TIMEZERO ) THEN
         BRK_Load2 = 1
      ELSE
         BRK_Load2 = 1
         IF ( TIME .GE. 7.0 ) BRK_Load2 = (1-1)
      ENDIF

! 120:[const] Real Constant 'VLL Base'
      RT_9 = 120.0

! 130:[const] Real Constant 
      RT_4 = 0.0

! 140:[const] Real Constant 'SQRT23'
      RT_10 = 0.8164965

! 150:[mult] Multiplier 
      RT_8 = RT_9 * RT_10

! 160:[div] Divider 
      IF (ABS(RT_8) .LT. 1.0E-100) THEN
         IF (RT_8 .LT. 0.0)  THEN
            RT_3 = -1.0E100 * Vload_abc
         ELSE
            RT_3 =  1.0E100 * Vload_abc
         ENDIF
      ELSE
         RT_3 = Vload_abc / RT_8
      ENDIF

! 170:[EPRI_PLL_18_1]  
      CALL EPRI_PLL_18_1Dyn(RT_1, RT_2, RT_3, RT_4, 20.0, 500.0, 75.0, 0&
     &.01)


! 180:[realpole] Real Pole 
!  Real_Pole
      RT_11 = REALPOLE(0,1,0,60.0,0.05,RT_1,0.0,-1.0E20,1.0E20)

! 190:[pgb] Output Channel 'freq_load'

      PGB(IPGB+5) = RT_11

! 220:[tpflt] Three Phase Fault 
      CALL E3PHFLT1_EXE(SS, (IBRCH+16), (IBRCH+17), (IBRCH+18), (IBRCH+1&
     &9), (IBRCH+20), (IBRCH+21),0,IT_1,7,0.01)
      LVD1_1 = (OPENBR( (IBRCH+16),SS).AND.OPENBR( (IBRCH+17),SS).AND.OP&
     &ENBR( (IBRCH+18),SS).AND.OPENBR( (IBRCH+19),SS).AND.OPENBR( (IBRCH&
     &+20),SS).AND.OPENBR( (IBRCH+21),SS))
      IVD1_1 = E_BtoI(LVD1_1)
      IF(FIRSTSTEP .OR. (IVD1_1 .NE. STORI(NSTORI))) THEN
         CALL PSCAD_AGI2(ICALL_NO,390030406,1-IVD1_1,"AG1")
         STORI(NSTORI) = IVD1_1
      ENDIF
      NSTORI = NSTORI + 1

! 230:[breaker3] 3 Phase Breaker 'BRK_Load1'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS, (IBRCH+40),0.005,1.0e+16,RTCF(NRTCF),1,NIN&
     &T(1.0-REAL(BRK_Load1)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+41),0.005,1.0e+16,RTCF(NRTCF),1,NIN&
     &T(1.0-REAL(BRK_Load1)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+42),0.005,1.0e+16,RTCF(NRTCF),1,NIN&
     &T(1.0-REAL(BRK_Load1)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH+40),SS))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH+41),SS))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH+42),SS))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1134322924,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1134322924,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1134322924,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH+40),SS))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH+41),SS))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH+42),SS))

! 240:[breaker3] 3 Phase Breaker 'BRK_Load2'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS, (IBRCH+61),0.005,1.0e+16,RTCF(NRTCF),1,NIN&
     &T(1.0-REAL(BRK_Load2)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+62),0.005,1.0e+16,RTCF(NRTCF),1,NIN&
     &T(1.0-REAL(BRK_Load2)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+63),0.005,1.0e+16,RTCF(NRTCF),1,NIN&
     &T(1.0-REAL(BRK_Load2)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH+61),SS))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH+62),SS))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH+63),SS))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1703487779,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1703487779,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1703487779,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH+61),SS))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH+62),SS))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH+63),SS))

! 1:[fixed_load] Fixed Load 
      CALL COMPONENT_ID(ICALL_NO,517717230)
      CALL LOAD3P2_EXE(SS, (IBRCH+10), (IBRCH+11), (IBRCH+12), (IBRCH+13&
     &), (IBRCH+14), (IBRCH+15),1.0)

! 1:[fixed_load] Fixed Load 
      CALL COMPONENT_ID(ICALL_NO,1932426153)
      CALL LOAD3P2_EXE(SS, (IBRCH+55), (IBRCH+56), (IBRCH+57), (IBRCH+58&
     &), (IBRCH+59), (IBRCH+60),1.0)

! 1:[fixed_load] Fixed Load 
      CALL COMPONENT_ID(ICALL_NO,1281722944)
      CALL LOAD3P2_EXE(SS, (IBRCH+34), (IBRCH+35), (IBRCH+36), (IBRCH+37&
     &), (IBRCH+38), (IBRCH+39),1.0)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 6) = RT_4
      STOF(ISTOF + 7) = Pbus1
      STOF(ISTOF + 8) = Pbus2
      STOF(ISTOF + 9) = Pbus3
      STOF(ISTOF + 13) = Qbus1
      STOF(ISTOF + 14) = Qbus2
      STOF(ISTOF + 15) = Qbus3
      STOF(ISTOF + 19) = Vbus1
      STOF(ISTOF + 20) = Vbus2
      STOF(ISTOF + 21) = Vbus3
      STOF(ISTOF + 25) = Ibus1
      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 26) = RT_8
      STOF(ISTOF + 27) = RT_9
      STOF(ISTOF + 28) = RT_10
      STOF(ISTOF + 32) = RT_11
      STOI(ISTOI + 2) = BRK_Load1
      STOI(ISTOI + 3) = BRK_Load2

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 2 + IT_0) = RT_3(IT_0)
         STOF(ISTOF + 9 + IT_0) = RT_5(IT_0)
         STOF(ISTOF + 15 + IT_0) = RT_6(IT_0)
         STOF(ISTOF + 21 + IT_0) = RT_7(IT_0)
         STOF(ISTOF + 28 + IT_0) = Vload_abc(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Sys_2_1Out()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    P3PH3         ! 
      REAL    Q3PH3         ! 
      REAL    VM3PH2        ! '3 Phase RMS Voltage Measurement'
      REAL    RMS3PH        ! '3 Phase RMS Measurement'
      REAL    REALPOLE      ! 
      REAL    EMTDC_VVDC    ! 
!     SUBR    EPRI_PLL_18_1Out  ! 
      REAL    VBRANCH       ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  In1(3), In2(3), NT_3(3)

! Control Signals
      REAL     RT_4, Pbus1, Pbus2, Pbus3, RT_5(3)
      REAL     Qbus1, Qbus2, Qbus3, RT_6(3)
      REAL     Vbus1, Vbus2, Vbus3, RT_7(3)
      REAL     Ibus1, RT_9, RT_10, Vload_abc(3)

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 11
      INODE     = NNODE + 2
      NNODE     = NNODE + 26
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 63
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_4     = STOF(ISTOF + 6)
      Pbus1    = STOF(ISTOF + 7)
      Pbus2    = STOF(ISTOF + 8)
      Pbus3    = STOF(ISTOF + 9)
      Qbus1    = STOF(ISTOF + 13)
      Qbus2    = STOF(ISTOF + 14)
      Qbus3    = STOF(ISTOF + 15)
      Vbus1    = STOF(ISTOF + 19)
      Vbus2    = STOF(ISTOF + 20)
      Vbus3    = STOF(ISTOF + 21)
      Ibus1    = STOF(ISTOF + 25)
      RT_9     = STOF(ISTOF + 27)
      RT_10    = STOF(ISTOF + 28)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_5(IT_0) = STOF(ISTOF + 9 + IT_0)
         RT_6(IT_0) = STOF(ISTOF + 15 + IT_0)
         RT_7(IT_0) = STOF(ISTOF + 21 + IT_0)
         Vload_abc(IT_0) = STOF(ISTOF + 28 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         In1(IT_0) = NODE(INODE + 0 + IT_0)
         In2(IT_0) = NODE(INODE + 3 + IT_0)
         NT_3(IT_0) = NODE(INODE + 12 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Sys_2_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+7), (IBRCH+8), (IBRCH+9),&
     &RTCF(IVD1_1+2),0)
      Pbus1 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+7), (IBRCH+8), (IBRCH+9),&
     &RTCF(IVD1_1+2),0)
      Qbus1 = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS, In1(1), In1(2), In1(3), RTCF(&
     &IVD1_1+2))
      Vbus1 = RVD1_1
      RVD1_1 = RMS3PH(( CBR((IBRCH+7), SS)),( CBR((IBRCH+8), SS)),( CBR(&
     &(IBRCH+9), SS)))
      RVD1_1 = REALPOLE(0,1,0,RTCF(IVD1_1+4),RTCF(IVD1_1+2),RVD1_1,0.0,0&
     &.0,RTCF(IVD1_1+2))
      Ibus1 = RVD1_1

! 20:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Vload_abc(1) = EMTDC_VVDC(SS, NT_3(1), 0)
      Vload_abc(2) = EMTDC_VVDC(SS, NT_3(2), 0)
      Vload_abc(3) = EMTDC_VVDC(SS, NT_3(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+4), (IBRCH+5), (IBRCH+6),&
     &RTCF(IVD1_1+2),0)
      Pbus2 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+4), (IBRCH+5), (IBRCH+6),&
     &RTCF(IVD1_1+2),0)
      Qbus2 = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS, NT_3(1), NT_3(2), NT_3(3), RT&
     &CF(IVD1_1+2))
      Vbus2 = RVD1_1

! 30:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3),&
     &RTCF(IVD1_1+2),0)
      Pbus3 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3),&
     &RTCF(IVD1_1+2),0)
      Qbus3 = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS, In2(1), In2(2), In2(3), RTCF(&
     &IVD1_1+2))
      Vbus3 = RVD1_1

! 70:[datamerge] Merges data signals into an array 
      RT_5(1) = Pbus1
      RT_5(2) = Pbus2
      RT_5(3) = Pbus3

! 80:[pgb] Output Channel 'P'

      DO IVD1_1 = 1, 3
         PGB(IPGB+1+IVD1_1-1) = RT_5(IVD1_1)
      ENDDO

! 90:[pgb] Output Channel 'Bus1_MVA'

      PGB(IPGB+4) = 207.846 * Ibus1

! 100:[datamerge] Merges data signals into an array 
      RT_6(1) = Qbus1
      RT_6(2) = Qbus2
      RT_6(3) = Qbus3

! 110:[datamerge] Merges data signals into an array 
      RT_7(1) = Vbus1
      RT_7(2) = Vbus2
      RT_7(3) = Vbus3

! 120:[const] Real Constant 'VLL Base'

      RT_9 = 120.0

! 130:[const] Real Constant 

      RT_4 = 0.0

! 140:[const] Real Constant 'SQRT23'

      RT_10 = 0.8164965

! 170:[EPRI_PLL_18_1]  
      CALL EPRI_PLL_18_1Out()


! 200:[pgb] Output Channel 'V'

      DO IVD1_1 = 1, 3
         PGB(IPGB+6+IVD1_1-1) = RT_7(IVD1_1)
      ENDDO

! 210:[pgb] Output Channel 'Q'

      DO IVD1_1 = 1, 3
         PGB(IPGB+9+IVD1_1-1) = RT_6(IVD1_1)
      ENDDO

! 220:[tpflt] Three Phase Fault 
!
! Multi-phase Fault Currents
!

! 230:[breaker3] 3 Phase Breaker 'BRK_Load1'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS, (IBRCH+40), (IBRCH+41), (IBRCH+42),0,0,0,IVD1_1&
     &,0.02,RVD1_1,RVD1_2)

! 240:[breaker3] 3 Phase Breaker 'BRK_Load2'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS, (IBRCH+61), (IBRCH+62), (IBRCH+63),0,0,0,IVD1_1&
     &,0.02,RVD1_1,RVD1_2)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 6) = RT_4
      STOF(ISTOF + 7) = Pbus1
      STOF(ISTOF + 8) = Pbus2
      STOF(ISTOF + 9) = Pbus3
      STOF(ISTOF + 13) = Qbus1
      STOF(ISTOF + 14) = Qbus2
      STOF(ISTOF + 15) = Qbus3
      STOF(ISTOF + 19) = Vbus1
      STOF(ISTOF + 20) = Vbus2
      STOF(ISTOF + 21) = Vbus3
      STOF(ISTOF + 25) = Ibus1
      STOF(ISTOF + 27) = RT_9
      STOF(ISTOF + 28) = RT_10

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 9 + IT_0) = RT_5(IT_0)
         STOF(ISTOF + 15 + IT_0) = RT_6(IT_0)
         STOF(ISTOF + 21 + IT_0) = RT_7(IT_0)
         STOF(ISTOF + 28 + IT_0) = Vload_abc(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Sys_2_1Dyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EPRI_PLL_18_1Dyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_4, RT_9, RT_10

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD1_5, RVD1_6

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 26
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 63
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 120:[const] Real Constant 'VLL Base'
      RT_9 = 120.0

! 130:[const] Real Constant 
      RT_4 = 0.0

! 140:[const] Real Constant 'SQRT23'
      RT_10 = 0.8164965

! 150:[mult] Multiplier 

! 160:[div] Divider 

! 170:[EPRI_PLL_18_1]  
      CALL EPRI_PLL_18_1Dyn_Begin()


! 180:[realpole] Real Pole 

! 190:[pgb] Output Channel 'freq_load'

! 220:[tpflt] Three Phase Fault 
      CALL E3PHFLT1_CFG(1000000.0,0.0)

! 230:[breaker3] 3 Phase Breaker 'BRK_Load1'
      CALL COMPONENT_ID(ICALL_NO,1134322924)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 240:[breaker3] 3 Phase Breaker 'BRK_Load2'
      CALL COMPONENT_ID(ICALL_NO,1703487779)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 1:[newpi] Coupled Pi Section Transmission Line 'Line1'
      CALL COMPONENT_ID(ICALL_NO,807018153)
      CALL PI3_SECTION_CFG(3,1,1, 120.0,100.0,60.0,1.0,0.0017,0.0046,0.0&
     &333,1.5,1.5,1.5,RVD1_1,RVD1_2,RVD1_3,RVD1_4,RVD1_5,RVD1_6,IVD1_1,I&
     &VD1_2,IVD1_3,IVD1_4)
      CALL E_BRANCH_CFG( (IBRCH+22),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+23),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+24),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+25),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+26),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+27),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+28),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+29),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+30),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+31),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+32),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+33),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL COUPLED_PI3_TF_CFG((IXFMR + 1),2,RVD1_1,RVD1_2,RVD1_4,RVD1_5)

! 1:[newpi] Coupled Pi Section Transmission Line 'Line1_1'
      CALL COMPONENT_ID(ICALL_NO,1190532695)
      CALL PI3_SECTION_CFG(3,1,1, 120.0,100.0,60.0,1.0,0.0017,0.0046,0.0&
     &333,1.5,1.5,1.5,RVD1_1,RVD1_2,RVD1_3,RVD1_4,RVD1_5,RVD1_6,IVD1_1,I&
     &VD1_2,IVD1_3,IVD1_4)
      CALL E_BRANCH_CFG( (IBRCH+43),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+44),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+45),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+46),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+47),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+48),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+49),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+50),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+51),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+52),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+53),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+54),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL COUPLED_PI3_TF_CFG((IXFMR + 2),2,RVD1_1,RVD1_2,RVD1_4,RVD1_5)

! 1:[fixed_load] Fixed Load 
      CALL COMPONENT_ID(ICALL_NO,517717230)
      CALL LOAD1P2_CFG(0,1,69.28,1.0,60.0,30.0,7.0,10.0,0.0,0.0,1.0,2.0,&
     &1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0)

! 1:[fixed_load] Fixed Load 
      CALL COMPONENT_ID(ICALL_NO,1932426153)
      CALL LOAD1P2_CFG(0,1,69.28,1.0,60.0,3.0,0.7,10.0,0.0,0.0,1.0,2.0,1&
     &.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0)

! 1:[fixed_load] Fixed Load 
      CALL COMPONENT_ID(ICALL_NO,1281722944)
      CALL LOAD1P2_CFG(0,1,69.28,1.0,60.0,3.0,0.7,10.0,0.0,0.0,1.0,2.0,1&
     &.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0)

      RETURN
      END

!=======================================================================

      SUBROUTINE Sys_2_1Out_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EPRI_PLL_18_1Out_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_3(3)

! Control Signals
      REAL     RT_4, RT_9, RT_10

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 26
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 63
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_3(IT_0) = NODE(INODE + 12 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(120.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(120.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 20:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(120.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(120.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 30:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(120.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(120.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 70:[datamerge] Merges data signals into an array 

! 80:[pgb] Output Channel 'P'

! 90:[pgb] Output Channel 'Bus1_MVA'

! 100:[datamerge] Merges data signals into an array 

! 110:[datamerge] Merges data signals into an array 

! 120:[const] Real Constant 'VLL Base'
      RT_9 = 120.0

! 130:[const] Real Constant 
      RT_4 = 0.0

! 140:[const] Real Constant 'SQRT23'
      RT_10 = 0.8164965

! 170:[EPRI_PLL_18_1]  
      CALL EPRI_PLL_18_1Out_Begin()


! 200:[pgb] Output Channel 'V'

! 210:[pgb] Output Channel 'Q'

      RETURN
      END

