!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
!     SUBR    PVFarm_GFL_GFM_2Dyn  ! 
!     SUBR    3PHVSRC       ! 3-Phase Source model

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4
      REAL     Vs, RT_1, RT_2, RT_3, Ph, Is(3)

! Internal Variables
      REAL     RVD2_1(2), RVD1_1, RVD1_2, RVD1_3
      REAL     RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 4
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 8
      INODE     = NNODE + 2
      NNODE     = NNODE + 5
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Vs       = STOF(ISTOF + 1)
      IT_1     = STOI(ISTOI + 1)
      RT_1     = STOF(ISTOF + 2)
      IT_2     = STOI(ISTOI + 2)
      RT_2     = STOF(ISTOF + 3)
      RT_3     = STOF(ISTOF + 4)
      IT_3     = STOI(ISTOI + 3)
      IT_4     = STOI(ISTOI + 4)
      Ph       = STOF(ISTOF + 5)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Is(IT_0) = STOF(ISTOF + 5 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[consti] Integer Constant 
      IT_2 = 120

! 20:[consti] Integer Constant 
      IT_1 = 30

! 30:[consti] Integer Constant 
      IT_4 = 0

! 40:[consti] Integer Constant 
      IT_3 = 0

! 50:[time-sig] Output of Simulation Time 
      RT_3 = TIME

! 60:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.0,RT_3,0.0,0.0,1.0,RVD2_1)
      RT_1 = RVD2_1(1)

! 70:[PVFarm_GFL_GFM_2]  
      CALL PVFarm_GFL_GFM_2Dyn()


! 80:[select] Two Input Selector 
      IF (NINT(RT_1) .EQ. RTCI(NRTCI)) THEN
         RT_2 = REAL(IT_2)
      ELSE
         RT_2 = REAL(IT_1)
      ENDIF
      NRTCI = NRTCI + 1
!

! 90:[gain] Gain Block 
!  Gain
      Vs = 0.816496580928 * RT_2

! 100:[select] Two Input Selector 
      IF (NINT(RT_1) .EQ. RTCI(NRTCI)) THEN
         Ph = REAL(IT_4)
      ELSE
         Ph = REAL(IT_3)
      ENDIF
      NRTCI = NRTCI + 1
!

! 110:[source_3] Three Phase Voltage Source Model 2 'Source 1'
! Three Phase Source: Source 1  Type: Ideal
!  Mag: externally controlled, 
      RVD1_1 = Vs
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3  = Ph*PI_BY180
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF  = NRTCF + 4
      CALL EMTDC_3PHVSRC(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3), RVD1_4, .T&
     &RUE., RVD1_1 , RVD1_2, RVD1_3)
!

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Vs
      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 2) = RT_1
      STOI(ISTOI + 2) = IT_2
      STOF(ISTOF + 3) = RT_2
      STOF(ISTOF + 4) = RT_3
      STOI(ISTOI + 3) = IT_3
      STOI(ISTOI + 4) = IT_4
      STOF(ISTOF + 5) = Ph

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 5 + IT_0) = Is(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PVFarm_GFL_GFM_2Out  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4
      REAL     Is(3)

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 5
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      IT_1     = STOI(ISTOI + 1)
      IT_2     = STOI(ISTOI + 2)
      IT_3     = STOI(ISTOI + 3)
      IT_4     = STOI(ISTOI + 4)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Is(IT_0) = STOF(ISTOF + 5 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[consti] Integer Constant 

      IT_2 = 120

! 20:[consti] Integer Constant 

      IT_1 = 30

! 30:[consti] Integer Constant 

      IT_4 = 0

! 40:[consti] Integer Constant 

      IT_3 = 0

! 70:[PVFarm_GFL_GFM_2]  
      CALL PVFarm_GFL_GFM_2Out()


! 110:[source_3] Three Phase Voltage Source Model 2 'Source 1'
      Is(1) = ( CBR((IBRCH+1), SS))
      Is(2) = ( CBR((IBRCH+2), SS))
      Is(3) = ( CBR((IBRCH+3), SS))

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = IT_1
      STOI(ISTOI + 2) = IT_2
      STOI(ISTOI + 3) = IT_3
      STOI(ISTOI + 4) = IT_4

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 5 + IT_0) = Is(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PVFarm_GFL_GFM_2Dyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 5
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[consti] Integer Constant 
      IT_2 = 120

! 20:[consti] Integer Constant 
      IT_1 = 30

! 30:[consti] Integer Constant 
      IT_4 = 0

! 40:[consti] Integer Constant 
      IT_3 = 0

! 50:[time-sig] Output of Simulation Time 

! 60:[compare] Single Input Level Comparator 

! 70:[PVFarm_GFL_GFM_2]  
      CALL PVFarm_GFL_GFM_2Dyn_Begin()


! 80:[select] Two Input Selector 
      RTCI(NRTCI) = 0
      NRTCI = NRTCI + 1

! 90:[gain] Gain Block 

! 100:[select] Two Input Selector 
      RTCI(NRTCI) = 0
      NRTCI = NRTCI + 1

! 110:[source_3] Three Phase Voltage Source Model 2 'Source 1'
      RTCF(NRTCF+1) = 60.0*TWO_PI
      RTCF(NRTCF+3) = 0.05
      NRTCF = NRTCF + 4

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PVFarm_GFL_GFM_2Out_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 5
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[consti] Integer Constant 
      IT_2 = 120

! 20:[consti] Integer Constant 
      IT_1 = 30

! 30:[consti] Integer Constant 
      IT_4 = 0

! 40:[consti] Integer Constant 
      IT_3 = 0

! 70:[PVFarm_GFL_GFM_2]  
      CALL PVFarm_GFL_GFM_2Out_Begin()


      RETURN
      END

