!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : PVFarm_GFL_GFM_2
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE PVFarm_GFL_GFM_2Dyn()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
!     SUBR    SimpleSF_15_2Dyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, Vbase
      REAL     Fbase, UN, Rated_MW, RT_5, Q_POC
      REAL     P_POC, Vrms_POC, Igrid_POC(3)
      REAL     RT_6, RT_7, RT_8, RT_9, inv_Srate
      REAL     RT_10, RT_11, RT_12, RT_13(7)
      REAL     RT_14(7), RT_15(7), RT_16(7)
      REAL     RT_17(7), RT_18(7), RT_19, RT_20
      REAL     RT_21, I_ph_p, I_ph_n, I_ph_z
      REAL     RT_22(3), RT_23(3), Inv_phasor(6)
      REAL     I_inv_p, I_inv_n, I_inv_z, Vgrid_p
      REAL     Vgrid_n, Vgrid_z, RT_24, RT_25
      REAL     RT_26, RT_27(7), RT_28(7)
      REAL     RT_29(7), RT_30(7), RT_31(7)
      REAL     RT_32(7), RT_33, RT_34, RT_35
      REAL     Vgrid_ph_p, Vgrid_ph_n, Vgrid_ph_z
      REAL     RT_36(3), RT_37(3)
      REAL     V_Inv_phasor(6), Irms_POC
      REAL     I_inv(3), Vgrid_POC(3)

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD2_1(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 159
      NPGB      = NPGB + 34
      INODE     = NNODE + 2
      NNODE     = NNODE + 14
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 15
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_3     = STOF(ISTOF + 3)
      RT_4     = STOF(ISTOF + 4)
      Vbase    = STOF(ISTOF + 5)
      Fbase    = STOF(ISTOF + 6)
      UN       = STOF(ISTOF + 7)
      Rated_MW = STOF(ISTOF + 8)
      RT_5     = STOF(ISTOF + 9)
      Q_POC    = STOF(ISTOF + 10)
      P_POC    = STOF(ISTOF + 11)
      Vrms_POC = STOF(ISTOF + 12)
      RT_6     = STOF(ISTOF + 16)
      RT_7     = STOF(ISTOF + 17)
      RT_8     = STOF(ISTOF + 18)
      RT_9     = STOF(ISTOF + 19)
      inv_Srate = STOF(ISTOF + 20)
      RT_10    = STOF(ISTOF + 21)
      RT_11    = STOF(ISTOF + 22)
      RT_12    = STOF(ISTOF + 23)
      RT_19    = STOF(ISTOF + 66)
      RT_20    = STOF(ISTOF + 67)
      RT_21    = STOF(ISTOF + 68)
      I_ph_p   = STOF(ISTOF + 69)
      I_ph_n   = STOF(ISTOF + 70)
      I_ph_z   = STOF(ISTOF + 71)
      I_inv_p  = STOF(ISTOF + 84)
      I_inv_n  = STOF(ISTOF + 85)
      I_inv_z  = STOF(ISTOF + 86)
      Vgrid_p  = STOF(ISTOF + 87)
      Vgrid_n  = STOF(ISTOF + 88)
      Vgrid_z  = STOF(ISTOF + 89)
      RT_24    = STOF(ISTOF + 90)
      RT_25    = STOF(ISTOF + 91)
      RT_26    = STOF(ISTOF + 92)
      RT_33    = STOF(ISTOF + 135)
      RT_34    = STOF(ISTOF + 136)
      RT_35    = STOF(ISTOF + 137)
      Vgrid_ph_p = STOF(ISTOF + 138)
      Vgrid_ph_n = STOF(ISTOF + 139)
      Vgrid_ph_z = STOF(ISTOF + 140)
      Irms_POC = STOF(ISTOF + 153)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Igrid_POC(IT_0) = STOF(ISTOF + 12 + IT_0)
         RT_22(IT_0) = STOF(ISTOF + 71 + IT_0)
         RT_23(IT_0) = STOF(ISTOF + 74 + IT_0)
         RT_36(IT_0) = STOF(ISTOF + 140 + IT_0)
         RT_37(IT_0) = STOF(ISTOF + 143 + IT_0)
         I_inv(IT_0) = STOF(ISTOF + 153 + IT_0)
         Vgrid_POC(IT_0) = STOF(ISTOF + 156 + IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         Inv_phasor(IT_0) = STOF(ISTOF + 77 + IT_0)
         V_Inv_phasor(IT_0) = STOF(ISTOF + 146 + IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         RT_13(IT_0) = STOF(ISTOF + 23 + IT_0)
         RT_14(IT_0) = STOF(ISTOF + 30 + IT_0)
         RT_15(IT_0) = STOF(ISTOF + 37 + IT_0)
         RT_16(IT_0) = STOF(ISTOF + 44 + IT_0)
         RT_17(IT_0) = STOF(ISTOF + 51 + IT_0)
         RT_18(IT_0) = STOF(ISTOF + 58 + IT_0)
         RT_27(IT_0) = STOF(ISTOF + 92 + IT_0)
         RT_28(IT_0) = STOF(ISTOF + 99 + IT_0)
         RT_29(IT_0) = STOF(ISTOF + 106 + IT_0)
         RT_30(IT_0) = STOF(ISTOF + 113 + IT_0)
         RT_31(IT_0) = STOF(ISTOF + 120 + IT_0)
         RT_32(IT_0) = STOF(ISTOF + 127 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PVFarm_GFL_GFM_2.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[time-sig] Output of Simulation Time 
      RT_5 = TIME

! 20:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,0.1,RT_5,0.0,0.0,1.0,RVD2_1)
      RT_3 = RVD2_1(1)

! 40:[const] Real Constant 
      RT_9 = 1.0

! 50:[const] Real Constant 'Pref'
      RT_7 = 80.0

! 60:[const] Real Constant 'Number of units'
      UN = 400.0

! 70:[const] Real Constant 'Vref'
      RT_4 = 1.05

! 80:[const] Real Constant 'Turbine Rated Active Power'
      Rated_MW = 0.25

! 90:[const] Real Constant 'Qref'
      RT_6 = 20.0

! 100:[const] Real Constant 'Hz'
      Fbase = 60.0

! 110:[const] Real Constant 'kV'
      Vbase = 33.0

! 160:[mult] Multiplier 
      RT_8 = UN * Rated_MW

! 360:[div] Divider 
      IF (ABS(RT_8) .LT. 1.0E-100) THEN
         IF (RT_8 .LT. 0.0)  THEN
            inv_Srate = -1.0E100 * RT_9
         ELSE
            inv_Srate =  1.0E100 * RT_9
         ENDIF
      ELSE
         inv_Srate = RT_9 / RT_8
      ENDIF

! 610:[gain] Gain Block 
!  Gain
      RT_2 = inv_Srate * RT_6

! 620:[gain] Gain Block 
!  Gain
      RT_1 = inv_Srate * RT_7

! 630:[SimpleSF_15_2]  
      CALL SimpleSF_15_2Dyn(RT_1, RT_2, NINT(RT_3), RT_4, NINT(UN), Fbas&
     &e, Rated_MW, Vbase, 0.65, 1.4, 0.2, 1, 1.0, 0.0, 1.0, -0.5, 5.0, 3&
     &0.0, 1, 0, 20.0, 200.0, 0.5, 20.0, 30.0, 0.0, 1.0, 0.5, 20.0, 0.1,&
     & 0.25, 0.5, 100.0, 3.0, 10.0, 22.22, 0.0, 0.01, 0.5, 20.0, 0.5, 20&
     &.0, 1.2, 0.8, 1.3, 0.2, 1.0, 20.0, 0.3, 0.01)


! 1:[xfmr-3p2w] 3 Phase 2 Winding Transformer 'T1'
!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT1_EXE( (IBRCH+10), (IBRCH+11), (IBRCH+12),SS,1.0,0)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 4) = RT_4
      STOF(ISTOF + 5) = Vbase
      STOF(ISTOF + 6) = Fbase
      STOF(ISTOF + 7) = UN
      STOF(ISTOF + 8) = Rated_MW
      STOF(ISTOF + 9) = RT_5
      STOF(ISTOF + 10) = Q_POC
      STOF(ISTOF + 11) = P_POC
      STOF(ISTOF + 12) = Vrms_POC
      STOF(ISTOF + 16) = RT_6
      STOF(ISTOF + 17) = RT_7
      STOF(ISTOF + 18) = RT_8
      STOF(ISTOF + 19) = RT_9
      STOF(ISTOF + 20) = inv_Srate
      STOF(ISTOF + 21) = RT_10
      STOF(ISTOF + 22) = RT_11
      STOF(ISTOF + 23) = RT_12
      STOF(ISTOF + 66) = RT_19
      STOF(ISTOF + 67) = RT_20
      STOF(ISTOF + 68) = RT_21
      STOF(ISTOF + 69) = I_ph_p
      STOF(ISTOF + 70) = I_ph_n
      STOF(ISTOF + 71) = I_ph_z
      STOF(ISTOF + 84) = I_inv_p
      STOF(ISTOF + 85) = I_inv_n
      STOF(ISTOF + 86) = I_inv_z
      STOF(ISTOF + 87) = Vgrid_p
      STOF(ISTOF + 88) = Vgrid_n
      STOF(ISTOF + 89) = Vgrid_z
      STOF(ISTOF + 90) = RT_24
      STOF(ISTOF + 91) = RT_25
      STOF(ISTOF + 92) = RT_26
      STOF(ISTOF + 135) = RT_33
      STOF(ISTOF + 136) = RT_34
      STOF(ISTOF + 137) = RT_35
      STOF(ISTOF + 138) = Vgrid_ph_p
      STOF(ISTOF + 139) = Vgrid_ph_n
      STOF(ISTOF + 140) = Vgrid_ph_z
      STOF(ISTOF + 153) = Irms_POC

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 12 + IT_0) = Igrid_POC(IT_0)
         STOF(ISTOF + 71 + IT_0) = RT_22(IT_0)
         STOF(ISTOF + 74 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 140 + IT_0) = RT_36(IT_0)
         STOF(ISTOF + 143 + IT_0) = RT_37(IT_0)
         STOF(ISTOF + 153 + IT_0) = I_inv(IT_0)
         STOF(ISTOF + 156 + IT_0) = Vgrid_POC(IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         STOF(ISTOF + 77 + IT_0) = Inv_phasor(IT_0)
         STOF(ISTOF + 146 + IT_0) = V_Inv_phasor(IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         STOF(ISTOF + 23 + IT_0) = RT_13(IT_0)
         STOF(ISTOF + 30 + IT_0) = RT_14(IT_0)
         STOF(ISTOF + 37 + IT_0) = RT_15(IT_0)
         STOF(ISTOF + 44 + IT_0) = RT_16(IT_0)
         STOF(ISTOF + 51 + IT_0) = RT_17(IT_0)
         STOF(ISTOF + 58 + IT_0) = RT_18(IT_0)
         STOF(ISTOF + 92 + IT_0) = RT_27(IT_0)
         STOF(ISTOF + 99 + IT_0) = RT_28(IT_0)
         STOF(ISTOF + 106 + IT_0) = RT_29(IT_0)
         STOF(ISTOF + 113 + IT_0) = RT_30(IT_0)
         STOF(ISTOF + 120 + IT_0) = RT_31(IT_0)
         STOF(ISTOF + 127 + IT_0) = RT_32(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PVFarm_GFL_GFM_2Out()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    P3PH3         ! 
      REAL    Q3PH3         ! 
!     SUBR    DGTL_RMS3     ! '3 Phase Digital RMS Meter'
!     SUBR    DGTL_RMS3A    ! '3 Phase Digital RMS Meter'
!     SUBR    MPHASE3PS     ! Phase Measurement in a 3p signal
!     SUBR    FTN180        ! FFT Calculation
!     SUBR    SimpleSF_15_2Out  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_1(3)

! Control Signals
      REAL     RT_4, Vbase, Fbase, UN, Rated_MW
      REAL     Q_POC, P_POC, Vrms_POC
      REAL     Igrid_POC(3), RT_6, RT_7, RT_9
      REAL     RT_10, RT_11, RT_12, RT_13(7)
      REAL     RT_14(7), RT_15(7), RT_16(7)
      REAL     RT_17(7), RT_18(7), RT_19, RT_20
      REAL     RT_21, I_ph_p, I_ph_n, I_ph_z
      REAL     RT_22(3), RT_23(3), Inv_phasor(6)
      REAL     I_inv_p, I_inv_n, I_inv_z, Vgrid_p
      REAL     Vgrid_n, Vgrid_z, RT_24, RT_25
      REAL     RT_26, RT_27(7), RT_28(7)
      REAL     RT_29(7), RT_30(7), RT_31(7)
      REAL     RT_32(7), RT_33, RT_34, RT_35
      REAL     Vgrid_ph_p, Vgrid_ph_n, Vgrid_ph_z
      REAL     RT_36(3), RT_37(3)
      REAL     V_Inv_phasor(6), Irms_POC
      REAL     I_inv(3), Vgrid_POC(3)

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 34
      INODE     = NNODE + 2
      NNODE     = NNODE + 14
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 15
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_4     = STOF(ISTOF + 4)
      Vbase    = STOF(ISTOF + 5)
      Fbase    = STOF(ISTOF + 6)
      UN       = STOF(ISTOF + 7)
      Rated_MW = STOF(ISTOF + 8)
      Q_POC    = STOF(ISTOF + 10)
      P_POC    = STOF(ISTOF + 11)
      Vrms_POC = STOF(ISTOF + 12)
      RT_6     = STOF(ISTOF + 16)
      RT_7     = STOF(ISTOF + 17)
      RT_9     = STOF(ISTOF + 19)
      RT_10    = STOF(ISTOF + 21)
      RT_11    = STOF(ISTOF + 22)
      RT_12    = STOF(ISTOF + 23)
      RT_19    = STOF(ISTOF + 66)
      RT_20    = STOF(ISTOF + 67)
      RT_21    = STOF(ISTOF + 68)
      I_ph_p   = STOF(ISTOF + 69)
      I_ph_n   = STOF(ISTOF + 70)
      I_ph_z   = STOF(ISTOF + 71)
      I_inv_p  = STOF(ISTOF + 84)
      I_inv_n  = STOF(ISTOF + 85)
      I_inv_z  = STOF(ISTOF + 86)
      Vgrid_p  = STOF(ISTOF + 87)
      Vgrid_n  = STOF(ISTOF + 88)
      Vgrid_z  = STOF(ISTOF + 89)
      RT_24    = STOF(ISTOF + 90)
      RT_25    = STOF(ISTOF + 91)
      RT_26    = STOF(ISTOF + 92)
      RT_33    = STOF(ISTOF + 135)
      RT_34    = STOF(ISTOF + 136)
      RT_35    = STOF(ISTOF + 137)
      Vgrid_ph_p = STOF(ISTOF + 138)
      Vgrid_ph_n = STOF(ISTOF + 139)
      Vgrid_ph_z = STOF(ISTOF + 140)
      Irms_POC = STOF(ISTOF + 153)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Igrid_POC(IT_0) = STOF(ISTOF + 12 + IT_0)
         RT_22(IT_0) = STOF(ISTOF + 71 + IT_0)
         RT_23(IT_0) = STOF(ISTOF + 74 + IT_0)
         RT_36(IT_0) = STOF(ISTOF + 140 + IT_0)
         RT_37(IT_0) = STOF(ISTOF + 143 + IT_0)
         I_inv(IT_0) = STOF(ISTOF + 153 + IT_0)
         Vgrid_POC(IT_0) = STOF(ISTOF + 156 + IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         Inv_phasor(IT_0) = STOF(ISTOF + 77 + IT_0)
         V_Inv_phasor(IT_0) = STOF(ISTOF + 146 + IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         RT_13(IT_0) = STOF(ISTOF + 23 + IT_0)
         RT_14(IT_0) = STOF(ISTOF + 30 + IT_0)
         RT_15(IT_0) = STOF(ISTOF + 37 + IT_0)
         RT_16(IT_0) = STOF(ISTOF + 44 + IT_0)
         RT_17(IT_0) = STOF(ISTOF + 51 + IT_0)
         RT_18(IT_0) = STOF(ISTOF + 58 + IT_0)
         RT_27(IT_0) = STOF(ISTOF + 92 + IT_0)
         RT_28(IT_0) = STOF(ISTOF + 99 + IT_0)
         RT_29(IT_0) = STOF(ISTOF + 106 + IT_0)
         RT_30(IT_0) = STOF(ISTOF + 113 + IT_0)
         RT_31(IT_0) = STOF(ISTOF + 120 + IT_0)
         RT_32(IT_0) = STOF(ISTOF + 127 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_1(IT_0) = NODE(INODE + 3 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PVFarm_GFL_GFM_2.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[ammeter] Current Meter 'I_inv'
      I_inv(1) = ( CBR((IBRCH+13), SS))
      I_inv(2) = ( CBR((IBRCH+14), SS))
      I_inv(3) = ( CBR((IBRCH+15), SS))

! 40:[const] Real Constant 

      RT_9 = 1.0

! 50:[const] Real Constant 'Pref'

      RT_7 = 80.0

! 60:[const] Real Constant 'Number of units'

      UN = 400.0

! 70:[const] Real Constant 'Vref'

      RT_4 = 1.05

! 80:[const] Real Constant 'Turbine Rated Active Power'

      Rated_MW = 0.25

! 90:[const] Real Constant 'Qref'

      RT_6 = 20.0

! 100:[const] Real Constant 'Hz'

      Fbase = 60.0

! 110:[const] Real Constant 'kV'

      Vbase = 33.0

! 120:[datatap] Scalar/Array Tap 
      RT_10 = I_inv(1)

! 130:[datatap] Scalar/Array Tap 
      RT_12 = I_inv(2)

! 140:[datatap] Scalar/Array Tap 
      RT_11 = I_inv(3)

! 150:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Igrid_POC(1) = ( CBR((IBRCH+1), SS))
      Igrid_POC(2) = ( CBR((IBRCH+2), SS))
      Igrid_POC(3) = ( CBR((IBRCH+3), SS))
      Vgrid_POC(1) = EMTDC_VVDC(SS, NT_1(1), NT_1(2))
      Vgrid_POC(2) = EMTDC_VVDC(SS, NT_1(2), NT_1(3))
      Vgrid_POC(3) = EMTDC_VVDC(SS, NT_1(3), NT_1(1))
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1399266266,RVD1_1,"Pd")
      P_POC = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1399266266,RVD1_1,"Qd")
      Q_POC = RVD1_1
      CALL DGTL_RMS3(256,SS,NT_1(1),NT_1(2),NT_1(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1399266266,RVD1_1,"Vd")
      Vrms_POC = RVD1_1
      CALL DGTL_RMS3A(256,( CBR((IBRCH+1), SS)),( CBR((IBRCH+2), SS)),( &
     &CBR((IBRCH+3), SS)),RTCF(IVD1_1+3),RTCF(IVD1_1+4),0.0,RVD1_1)
      Irms_POC = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS, NT_1(1), 0)
      RVD1_3 = EMTDC_VVDC(SS, NT_1(2), 0)
      RVD1_4 = EMTDC_VVDC(SS, NT_1(3), 0)
      CALL MPHASE3PS(1, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,1399266266,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,1399266266,1,"hide2")
      ENDIF

! 170:[datatap] Scalar/Array Tap 
      RT_24 = Vgrid_POC(1)

! 180:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL COMPONENT_ID(ICALL_NO,1130419715)
      CALL FTN180(0,0,7,1,60.0,60.0,RT_10,IVD1_1,RT_13,RT_17,RT_19)
      CALL FTN180(0,0,7,1,60.0,60.0,RT_12,IVD1_1,RT_16,RT_18,RT_21)
      CALL FTN180(0,0,7,1,60.0,60.0,RT_11,IVD1_1,RT_14,RT_15,RT_20)
      CALL FTSEQN(7,0,RT_13,RT_16,RT_14,RT_17,RT_18,RT_15)
!

! 190:[datatap] Scalar/Array Tap 
      I_ph_z = RT_15(1)

! 200:[datatap] Scalar/Array Tap 
      RT_26 = Vgrid_POC(2)

! 210:[datatap] Scalar/Array Tap 
      RT_25 = Vgrid_POC(3)

! 220:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL COMPONENT_ID(ICALL_NO,1653675280)
      CALL FTN180(0,0,7,1,60.0,60.0,RT_24,IVD1_1,RT_27,RT_31,RT_33)
      CALL FTN180(0,0,7,1,60.0,60.0,RT_26,IVD1_1,RT_30,RT_32,RT_35)
      CALL FTN180(0,0,7,1,60.0,60.0,RT_25,IVD1_1,RT_28,RT_29,RT_34)
      CALL FTSEQN(7,0,RT_27,RT_30,RT_28,RT_31,RT_32,RT_29)
!

! 230:[datatap] Scalar/Array Tap 
      Vgrid_ph_z = RT_29(1)

! 240:[datatap] Scalar/Array Tap 
      Vgrid_ph_n = RT_32(1)

! 250:[datatap] Scalar/Array Tap 
      Vgrid_ph_p = RT_31(1)

! 260:[datatap] Scalar/Array Tap 
      I_ph_n = RT_18(1)

! 270:[datatap] Scalar/Array Tap 
      I_ph_p = RT_17(1)

! 280:[datatap] Scalar/Array Tap 
      Vgrid_z = RT_28(1)

! 290:[datatap] Scalar/Array Tap 
      Vgrid_n = RT_30(1)

! 300:[datatap] Scalar/Array Tap 
      Vgrid_p = RT_27(1)

! 310:[datatap] Scalar/Array Tap 
      I_inv_z = RT_14(1)

! 320:[datatap] Scalar/Array Tap 
      I_inv_n = RT_16(1)

! 330:[datatap] Scalar/Array Tap 
      I_inv_p = RT_13(1)

! 340:[datamerge] Merges data signals into an array 
      RT_36(1) = Vgrid_p
      RT_36(2) = Vgrid_n
      RT_36(3) = Vgrid_z

! 350:[datamerge] Merges data signals into an array 
      RT_22(1) = I_inv_p
      RT_22(2) = I_inv_n
      RT_22(3) = I_inv_z

! 370:[pgb] Output Channel 'Irms_POC'

      PGB(IPGB+1) = Irms_POC

! 380:[pgb] Output Channel 'Q_POC'

      PGB(IPGB+2) = Q_POC

! 390:[pgb] Output Channel 'Vgrid_ph_z'

      PGB(IPGB+3) = Vgrid_ph_z

! 400:[pgb] Output Channel 'P_POC'

      PGB(IPGB+4) = P_POC

! 410:[pgb] Output Channel 'Vgrid_ph_n'

      PGB(IPGB+5) = Vgrid_ph_n

! 420:[pgb] Output Channel 'I_ph_z'

      PGB(IPGB+6) = I_ph_z

! 430:[pgb] Output Channel 'Vrms_POC'

      PGB(IPGB+7) = Vrms_POC

! 440:[pgb] Output Channel 'Vgrid_ph_p'

      PGB(IPGB+8) = Vgrid_ph_p

! 450:[pgb] Output Channel 'I_ph_n'

      PGB(IPGB+9) = I_ph_n

! 460:[pgb] Output Channel 'Igrid_POC'

      DO IVD1_1 = 1, 3
         PGB(IPGB+10+IVD1_1-1) = Igrid_POC(IVD1_1)
      ENDDO

! 470:[pgb] Output Channel 'I_ph_p'

      PGB(IPGB+13) = I_ph_p

! 480:[pgb] Output Channel 'Vgrid_POC'

      DO IVD1_1 = 1, 3
         PGB(IPGB+14+IVD1_1-1) = Vgrid_POC(IVD1_1)
      ENDDO

! 490:[pgb] Output Channel 'Vgrid_z'

      PGB(IPGB+17) = Vgrid_z

! 500:[pgb] Output Channel 'Vgrid_n'

      PGB(IPGB+18) = Vgrid_n

! 510:[pgb] Output Channel 'I_inv_z'

      PGB(IPGB+19) = I_inv_z

! 520:[pgb] Output Channel 'Vgrid_p'

      PGB(IPGB+20) = Vgrid_p

! 530:[pgb] Output Channel 'I_inv_n'

      PGB(IPGB+21) = I_inv_n

! 540:[pgb] Output Channel 'I_inv_p'

      PGB(IPGB+22) = I_inv_p

! 550:[datamerge] Merges data signals into an array 
      RT_37(1) = Vgrid_ph_z
      RT_37(2) = Vgrid_ph_n
      RT_37(3) = Vgrid_ph_p

! 560:[datamerge] Merges data signals into an array 
      RT_23(1) = I_ph_z
      RT_23(2) = I_ph_n
      RT_23(3) = I_ph_p

! 570:[vector_interlace] Vector Interlace 
      DO IVD1_1 = 1, 3
        V_Inv_phasor(2*IVD1_1-1) = RT_36(IVD1_1)
        V_Inv_phasor(2*IVD1_1  ) = RT_37(IVD1_1)
      ENDDO

! 580:[pgb] Output Channel 'V_Inv_phasor'

      DO IVD1_1 = 1, 6
         PGB(IPGB+23+IVD1_1-1) = V_Inv_phasor(IVD1_1)
      ENDDO

! 590:[vector_interlace] Vector Interlace 
      DO IVD1_1 = 1, 3
        Inv_phasor(2*IVD1_1-1) = RT_22(IVD1_1)
        Inv_phasor(2*IVD1_1  ) = RT_23(IVD1_1)
      ENDDO

! 600:[pgb] Output Channel 'Inv_phasor'

      DO IVD1_1 = 1, 6
         PGB(IPGB+29+IVD1_1-1) = Inv_phasor(IVD1_1)
      ENDDO

! 630:[SimpleSF_15_2]  
      CALL SimpleSF_15_2Out()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 4) = RT_4
      STOF(ISTOF + 5) = Vbase
      STOF(ISTOF + 6) = Fbase
      STOF(ISTOF + 7) = UN
      STOF(ISTOF + 8) = Rated_MW
      STOF(ISTOF + 10) = Q_POC
      STOF(ISTOF + 11) = P_POC
      STOF(ISTOF + 12) = Vrms_POC
      STOF(ISTOF + 16) = RT_6
      STOF(ISTOF + 17) = RT_7
      STOF(ISTOF + 19) = RT_9
      STOF(ISTOF + 21) = RT_10
      STOF(ISTOF + 22) = RT_11
      STOF(ISTOF + 23) = RT_12
      STOF(ISTOF + 66) = RT_19
      STOF(ISTOF + 67) = RT_20
      STOF(ISTOF + 68) = RT_21
      STOF(ISTOF + 69) = I_ph_p
      STOF(ISTOF + 70) = I_ph_n
      STOF(ISTOF + 71) = I_ph_z
      STOF(ISTOF + 84) = I_inv_p
      STOF(ISTOF + 85) = I_inv_n
      STOF(ISTOF + 86) = I_inv_z
      STOF(ISTOF + 87) = Vgrid_p
      STOF(ISTOF + 88) = Vgrid_n
      STOF(ISTOF + 89) = Vgrid_z
      STOF(ISTOF + 90) = RT_24
      STOF(ISTOF + 91) = RT_25
      STOF(ISTOF + 92) = RT_26
      STOF(ISTOF + 135) = RT_33
      STOF(ISTOF + 136) = RT_34
      STOF(ISTOF + 137) = RT_35
      STOF(ISTOF + 138) = Vgrid_ph_p
      STOF(ISTOF + 139) = Vgrid_ph_n
      STOF(ISTOF + 140) = Vgrid_ph_z
      STOF(ISTOF + 153) = Irms_POC

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 12 + IT_0) = Igrid_POC(IT_0)
         STOF(ISTOF + 71 + IT_0) = RT_22(IT_0)
         STOF(ISTOF + 74 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 140 + IT_0) = RT_36(IT_0)
         STOF(ISTOF + 143 + IT_0) = RT_37(IT_0)
         STOF(ISTOF + 153 + IT_0) = I_inv(IT_0)
         STOF(ISTOF + 156 + IT_0) = Vgrid_POC(IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         STOF(ISTOF + 77 + IT_0) = Inv_phasor(IT_0)
         STOF(ISTOF + 146 + IT_0) = V_Inv_phasor(IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         STOF(ISTOF + 23 + IT_0) = RT_13(IT_0)
         STOF(ISTOF + 30 + IT_0) = RT_14(IT_0)
         STOF(ISTOF + 37 + IT_0) = RT_15(IT_0)
         STOF(ISTOF + 44 + IT_0) = RT_16(IT_0)
         STOF(ISTOF + 51 + IT_0) = RT_17(IT_0)
         STOF(ISTOF + 58 + IT_0) = RT_18(IT_0)
         STOF(ISTOF + 92 + IT_0) = RT_27(IT_0)
         STOF(ISTOF + 99 + IT_0) = RT_28(IT_0)
         STOF(ISTOF + 106 + IT_0) = RT_29(IT_0)
         STOF(ISTOF + 113 + IT_0) = RT_30(IT_0)
         STOF(ISTOF + 120 + IT_0) = RT_31(IT_0)
         STOF(ISTOF + 127 + IT_0) = RT_32(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PVFarm_GFL_GFM_2Dyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    SimpleSF_15_2Dyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_4, Vbase, Fbase, UN, Rated_MW
      REAL     RT_6, RT_7, RT_9

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD1_5, RVD1_6

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 14
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 15
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[time-sig] Output of Simulation Time 

! 20:[compare] Single Input Level Comparator 

! 40:[const] Real Constant 
      RT_9 = 1.0

! 50:[const] Real Constant 'Pref'
      RT_7 = 80.0

! 60:[const] Real Constant 'Number of units'
      UN = 400.0

! 70:[const] Real Constant 'Vref'
      RT_4 = 1.05

! 80:[const] Real Constant 'Turbine Rated Active Power'
      Rated_MW = 0.25

! 90:[const] Real Constant 'Qref'
      RT_6 = 20.0

! 100:[const] Real Constant 'Hz'
      Fbase = 60.0

! 110:[const] Real Constant 'kV'
      Vbase = 33.0

! 160:[mult] Multiplier 

! 360:[div] Divider 

! 610:[gain] Gain Block 

! 620:[gain] Gain Block 

! 630:[SimpleSF_15_2]  
      CALL SimpleSF_15_2Dyn_Begin(NINT(UN), Fbase, Rated_MW, Vbase, 0.65&
     &, 1.4, 0.2, 1, 0, 0.1, 0.25, 0.2)


! 1:[xfmr-3p2w] 3 Phase 2 Winding Transformer 'T1'
      CALL COMPONENT_ID(ICALL_NO,4657390)
      RVD1_1 = ONE_3RD*100.0
      RVD1_2 = 33.0
      RVD1_3 = 120.0*SQRT_1BY3
      CALL E_TF2W_CFG((IXFMR + 1),0,RVD1_1,60.0,0.08,0.0,RVD1_2,RVD1_3,1&
     &.0)
      CALL E_TF2W_CFG((IXFMR + 2),0,RVD1_1,60.0,0.08,0.0,RVD1_2,RVD1_3,1&
     &.0)
      CALL E_TF2W_CFG((IXFMR + 3),0,RVD1_1,60.0,0.08,0.0,RVD1_2,RVD1_3,1&
     &.0)
      IF (0.0 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.0
        RVD1_4 = 6.0/(100.0*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG( (IBRCH+4),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+5),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+6),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+7),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+8),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+9),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT1_CFG( (IBRCH+10), (IBRCH+11), (IBRCH+12),SS,RVD1_1,RVD1_&
     &3,0.2,1.17,60.0,0.0,1.0,0.0)

      RETURN
      END

!=======================================================================

      SUBROUTINE PVFarm_GFL_GFM_2Out_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    SimpleSF_15_2Out_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_1(3)

! Control Signals
      REAL     RT_4, Vbase, Fbase, UN, Rated_MW
      REAL     RT_6, RT_7, RT_9

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 14
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 15
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_1(IT_0) = NODE(INODE + 3 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[const] Real Constant 
      RT_9 = 1.0

! 50:[const] Real Constant 'Pref'
      RT_7 = 80.0

! 60:[const] Real Constant 'Number of units'
      UN = 400.0

! 70:[const] Real Constant 'Vref'
      RT_4 = 1.05

! 80:[const] Real Constant 'Turbine Rated Active Power'
      Rated_MW = 0.25

! 90:[const] Real Constant 'Qref'
      RT_6 = 20.0

! 100:[const] Real Constant 'Hz'
      Fbase = 60.0

! 110:[const] Real Constant 'kV'
      Vbase = 33.0

! 120:[datatap] Scalar/Array Tap 

! 130:[datatap] Scalar/Array Tap 

! 140:[datatap] Scalar/Array Tap 

! 150:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(Vbase) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vbase)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = Fbase
      IF (ABS(1.758) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(1.758)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 170:[datatap] Scalar/Array Tap 

! 180:[fft] On-Line Frequency Scanner 

! 190:[datatap] Scalar/Array Tap 

! 200:[datatap] Scalar/Array Tap 

! 210:[datatap] Scalar/Array Tap 

! 220:[fft] On-Line Frequency Scanner 

! 230:[datatap] Scalar/Array Tap 

! 240:[datatap] Scalar/Array Tap 

! 250:[datatap] Scalar/Array Tap 

! 260:[datatap] Scalar/Array Tap 

! 270:[datatap] Scalar/Array Tap 

! 280:[datatap] Scalar/Array Tap 

! 290:[datatap] Scalar/Array Tap 

! 300:[datatap] Scalar/Array Tap 

! 310:[datatap] Scalar/Array Tap 

! 320:[datatap] Scalar/Array Tap 

! 330:[datatap] Scalar/Array Tap 

! 340:[datamerge] Merges data signals into an array 

! 350:[datamerge] Merges data signals into an array 

! 370:[pgb] Output Channel 'Irms_POC'

! 380:[pgb] Output Channel 'Q_POC'

! 390:[pgb] Output Channel 'Vgrid_ph_z'

! 400:[pgb] Output Channel 'P_POC'

! 410:[pgb] Output Channel 'Vgrid_ph_n'

! 420:[pgb] Output Channel 'I_ph_z'

! 430:[pgb] Output Channel 'Vrms_POC'

! 440:[pgb] Output Channel 'Vgrid_ph_p'

! 450:[pgb] Output Channel 'I_ph_n'

! 460:[pgb] Output Channel 'Igrid_POC'

! 470:[pgb] Output Channel 'I_ph_p'

! 480:[pgb] Output Channel 'Vgrid_POC'

! 490:[pgb] Output Channel 'Vgrid_z'

! 500:[pgb] Output Channel 'Vgrid_n'

! 510:[pgb] Output Channel 'I_inv_z'

! 520:[pgb] Output Channel 'Vgrid_p'

! 530:[pgb] Output Channel 'I_inv_n'

! 540:[pgb] Output Channel 'I_inv_p'

! 550:[datamerge] Merges data signals into an array 

! 560:[datamerge] Merges data signals into an array 

! 570:[vector_interlace] Vector Interlace 

! 580:[pgb] Output Channel 'V_Inv_phasor'

! 590:[vector_interlace] Vector Interlace 

! 600:[pgb] Output Channel 'Inv_phasor'

! 630:[SimpleSF_15_2]  
      CALL SimpleSF_15_2Out_Begin(NINT(UN), Fbase, Rated_MW, Vbase, 0.65&
     &, 1.4, 0.2, 1, 0, 0.1, 0.25, 0.2)


      RETURN
      END

